### ISSUE TITLE
Real time tracking of buses

### ISSUE THREAD

**Issue by santosh** [dhirajt/dtc_bus_routes#4]
If you look in [this video](https://youtu.be/RrPZza_vZ3w?t=16m36s), you'll find out that Chicago Transit Authority have a very good API for developers. Yet in India, government don't have public data. 

I was inspired by the problem solving in that video that we should have such API. No matter even through OUR API.

We can't have the GPS coordinates, and real-time tracking and stuff, that I know because DTC buses are not GPS enabled. There is also a time field for BUS from which we can predict where the bus actually would be at given time. There are many more data that are provided by Chicago Transit Authority.

How about my idea? Please see that video if you haven't and tell me your thoughts. I'd be happy to hear from you. :smiley:

**Comment by santosh** [comment]
I have also been seeing [this proposal](https://data.gov.in/suggest-dataset/suggest-dataset-105364) at Open Government Data website. Can we have simliar suggestion for the problem we have?

See I don't intarnals of DTC neither govt. nor totally of Python. I am just suggesting. We can work together on this.

**Comment by santosh** [comment]
I wonder how Google Maps manages it!

**Comment by dhirajt** [comment]
@santosh Cool video! 

As you said the problem is that we don't have GPS enabled buses nor any api from DTC. We don't even have proper bus stop and time details. I had to manually insert the entries into the database after verifying the names and location on google maps one by one (imagine my pain! :cry: ). The only thing we get from DTC is this badly formatted :mask: csv (http://www.delhi.gov.in/wps/wcm/connect/66af22004e01eacd841ea4d4f77cccee/Time+Table+of+DTC+Bus+Routes.xlsx?MOD=AJPERES&lmod=-322799927)

We can request the data from government data site but i don't think they'll update it anytime soon. :disappointed: 

I am open to working together on this. Just let me know what i can do :smiley: 

To predict indirect routes we need to have co-ordinates of these stops. I am manually adding those in the database but i still have a long way to go (100-120 done out of about 1000 stops). As soon as it's completed i can start working on recommending indirect routes. 

My main concern is the accuracy of data set since i've manually added them in the database errors must have crept in. I am not sure how can we validate the data already there since this is tedious work, doing it manually. Let me know if you have any suggestions regarding this.

**Comment by sarthakbhatia** [comment]
Well I think we can add GPS systems (cheap ones). Though we might have to meet some people for that and pitch the idea. And I was thinking more on the lines of PressPlay like thingy for Public Transit.

Check out PressPlay or Ozone Wifi at Mcdonald's.

We can certaainly use it as GPS plus make a standalone trackers.

**Comment by dhirajt** [comment]
@sarthakbhatia Actually the idea to add GPS to buses has already been implemented in a few buses but i don't think they'll release the API publicly. We'll have to figure out a way to get the information from users.

**Comment by sarthakbhatia** [comment]
@dhirajt Yes that is what I meant with onboard entertainment system in Buses. Where users can access limited movies,music and some particular websites. And using the same we can add GPS addon. Or use some specific app GPS. A lot can be done.

**Comment by vivekbhatt0601** [comment]
Hi Dhirajt,
I saw your web app, and you did a great work.
I was just wondering if you are interested for working together on an app for similar kind of task?

**Comment by dhirajt** [comment]
@vivekbhatt0601 Shoot me a mail at dhirajk.92  @ gmail.

**Comment by santosh** [comment]
- That XML link gives a 404 now.
- I'm going to close this ticket, but you are open to reference this ticket in future.
- @dhirajt let's make something like this for public.
